version: "3.9"

services:
  php-fpm:
    image: itstreason/apt-repo-php:0.0.3
    build:
      context: "."
      dockerfile: "docker/php-fpm/Dockerfile"
      target: "production"

  nginx:
    image: itstreason/apt-repo-nginx:0.0.3
    build:
      context: "."
      dockerfile: "docker/nginx/Dockerfile"
      target: "production"
